apiVersion: project.openshift.io/v1
description: "xerter"
displayName: xerter
kind: ProjectRequest
metadata:
    name: xerter

# run below command manually 
#oc new-app --name=repure --docker-image="docker.io/openshift/hello-openshift"

